cabal-version:      3.0
name:               backend
version:            0.1.0.0
synopsis:           Servant backend for HWSMLogistics
build-type:         Simple

executable backend
  main-is:          Main.hs
  other-modules:    Backend
                  , Backend.Ws
                  , DB
  hs-source-dirs:   app, src
  build-depends:    base >= 4.14 && < 5
                  , common
                  , servant
                  , servant-server
                  , warp
                  , wai
                  , aeson
                  , text
                  , bytestring
                  , mysql-simple
                  , wai-cors
                  , wai-extra
                  , http-types
                  , wai-websockets
                  , websockets
                  , stm
                  , time

