cabal-version: 3.0
name: common
version: 0.1.0.0
build-type: Simple

library
  exposed-modules:
      Common.Api
    , Common.Types
  hs-source-dirs: src
  default-language: Haskell2010
  build-depends:
      base >= 4.14 && < 5
    , servant
    , servant-server
    , servant-openapi3
    , openapi3
    , text
    , time
    , uuid
    , aeson
    , http-api-data

executable generate-openapi
  main-is: GenerateOpenAPI.hs
  other-modules:
      Common.Api
    , Common.Types
  hs-source-dirs: app, src
  default-language: Haskell2010
  build-depends:
      base >= 4.14 && < 5
    , common
    , servant
    , servant-server
    , servant-openapi3
    , openapi3
    , http-api-data
    , aeson
    , bytestring
    , text
    , time
    , uuid
    , directory
    , filepath

executable generate-ts
  main-is: GenerateTS.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
      base >= 4.14 && < 5
    , directory
    , filepath
